## Train a  Bernoulli-Bernoulli RBM (BBRBM) to fit XOR calculations

In [1]:
import numpy as np
from tfrbm.bbrbm import BBRBM

In [2]:
r = BBRBM(n_visible=3,n_hidden=13)

In [3]:
x = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]])

In [4]:
errs = r.fit(x,n_epoches = 3001)

Epoch: 0 Train error: 0.2210
Epoch: 1000 Train error: 0.1357
Epoch: 2000 Train error: 0.0698
Epoch: 3000 Train error: 0.0252


### Test predictions

In [5]:
# # 0 xor 0 = 0
r.predict(data = [[0,0,-1]], positions_to_predict = [2])

All possibilities:  [[0 0 0]
 [0 0 1]]
energy: [-9.074352 -9.391294]
best_answer_index: 1


array([0, 0, 1])

In [6]:
# 0 xor 1 = 1
r.predict(data = [[0,1,-1]], positions_to_predict = [2])

All possibilities:  [[0 1 0]
 [0 1 1]]
energy: [-9.135985  -9.8089285]
best_answer_index: 1


array([0, 1, 1])

In [7]:
# 1 xor 0 = 1
r.predict(data = [[1,0,-1]], positions_to_predict = [2])

All possibilities:  [[1 0 0]
 [1 0 1]]
energy: [-9.510984 -9.222629]
best_answer_index: 0


array([1, 0, 0])

In [8]:
# 1 xor 1 = 1
r.predict(data = [[1,1,-1]], positions_to_predict = [2])

All possibilities:  [[1 1 0]
 [1 1 1]]
energy: [-9.558853 -9.110913]
best_answer_index: 0


array([1, 1, 0])